# Generated by Django 3.2.12 on 2022-03-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Product',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='products',
            name='b_category',
            field=models.CharField(choices=[('MTW', 'boytopwear'), ('MBW', 'boybottomwear')], default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='e_category',
            field=models.CharField(choices=[('M', 'Mobiles'), ('L', 'Laptops')], default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='g_category',
            field=models.CharField(choices=[('FTW', 'girltopwear'), ('FBW', 'girlbottomwear')], default=0, max_length=200),
        ),
    ]
